{
 "title": "MB8611 Cable Modem",
 "description": "Dashboard for MB8611 prometheus metrics provided by https://github.com/jahkeup/prometheus-moto-exporter. General dashboard layout inspired by https://github.com/ickymettle/netgear_cm_exporter",
 "tags": [
  "mb8611",
  "cable modem",
  "motorola",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Cable Modem Status", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  {
   "title": "Cable Modem Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "moto_device_hardware_info{job=\"mb8611\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Downstream Channel Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "moto_downstream_channel_power_dbmv{job=\"mb8611\"}",
     "legendFormat": "Downstream {{channel}}"
    }
   ]
  },
  {
   "title": "Downstream Locked Channels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(moto_downstream_channel_locked{job=\"mb8611\"})",
     "legendFormat": "Upstream Locked Channels"
    }
   ]
  },
  {
   "title": "Downstream SnR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "moto_downstream_channel_signal_noise_ratio{job=\"mb8611\"}",
     "legendFormat": "DS Channel {{channel}}"
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Upstream Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "moto_upstream_channel_power_dbmv{job=\"mb8611\"}",
     "legendFormat": "Upstream {{channel}}"
    }
   ]
  },
  {
   "title": "Upstream Symbol Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(moto_upstream_channel_symbol_rate{job=\"mb8611\"})",
     "legendFormat": "Upstream Symbol Rate (avg)"
    }
   ]
  },
  {
   "title": "Upstream Locked Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum(moto_upstream_channel_locked{job=\"mb8611\"})",
     "legendFormat": "Upstream Locked Channels"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Downstream Corrected by Channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(moto_downstream_channel_corrected_total{job=\"mb8611\"}[$__rate_interval])",
     "legendFormat": "Downstream {{channel}}"
    }
   ]
  },
  {
   "title": "Downstream Uncorrected by Channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(moto_downstream_channel_uncorrected_total{job=\"mb8611\"}[$__rate_interval])",
     "legendFormat": "Downstream {{channel}}"
    }
   ]
  }
 ]
}